"""initial

Revision ID: a1e240de9660
Revises: 
Create Date: 2017-01-16 17:59:44.942647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e240de9660'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_facts',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign', sa.String(length=128), nullable=False),
    sa.Column('campaign_state', sa.Enum('enabled', 'disabled', name='campaign_states'), nullable=False),
    sa.Column('campaign_serving_status', sa.Enum('enabled', 'disabled', name='campaign_serving_statuses'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('budget_explicit_share', sa.Boolean(), nullable=False),
    sa.Column('label_ids', sa.JSON(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('invalid_clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('search_lost_is', sa.Float(), nullable=True),
    sa.Column('avg_position', sa.Float(), nullable=True),
    sa.Column('interactions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'customer_id', 'campaign_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_facts')
    # ### end Alembic commands ###
